version: "3"
services:
    atariworldmodel:
        build: .
        user: $DC_USER
        volumes:
        - ".:/workspace"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
        environment:
        - "DISPLAY=:0.0"
        devices:
        - "/dev/dri:/dev/dri"
